language: node_js
node_js:
  - node

env:
  - CXX=g++-4.8
  - CPATH=$TRAVIS_BUILD_DIR/LoRaMac:$TRAVIS_BUILD_DIR/LoRaMac/crypto
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8