language: node_js
node_js:
  - "6"
  - "5"
  - "4"

env:
  - CXX=g++-4.8
  - CPATH=$HOME/node-lorawancrypto/LoRaMac:$HOME/node-lorawancrypto/LoRaMac/crypto
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8